import { shuffle } from 'fast-shuffle';
import exampleImg1 from '../assets/images/cars.jpg';
import exampleImg2 from '../assets/images/balloon.jpg';
import exampleImg3 from '../assets/images/boardgame.jpg';
import exampleImg4 from '../assets/images/book.jpg';
import exampleImg5 from '../assets/images/exam01.jpg';
import exampleImg6 from '../assets/images/exam02.jpg';
import exampleImg7 from '../assets/images/exam03.jpg';
import exampleImg8 from '../assets/images/puzzle.jpg';

const imagePaths = [
  exampleImg1,
  exampleImg2,
  exampleImg3,
  exampleImg4,
  exampleImg5,
  exampleImg6,
  exampleImg7,
  exampleImg8,
];
export type CategoryType =
  | 'gift'
  | 'intelligence'
  | 'fiveSenses'
  | 'emotion'
  | 'society';

export type CategoryAgeType =
  | '모두 보기'
  | '0-6'
  | '7-12'
  | '12-18'
  | '19-24'
  | '2-3'
  | 'over3';

export interface ProductProp {
  productId: number;
  productTitle: string;
  productPrice: number;
  productRating: number;
  productRatingCount: number;
  productImg: string;
  productCategory: CategoryType[];
  productCategoryAge: CategoryAgeType[];
}

export interface Products {
  products: ProductProp[];
}

// 랜덤 제품 100개 만들기
// 랜덤 숫자 뽑기
const getRandomInt = (min: number, max: number): number =>
  Math.floor(Math.random() * (max - min + 1)) + min;

// 1개~3개 카테고리를 랜덤하게 해주기
const getRandomSubset = <T,>(array: T[]): T[] => {
  const minCount = 1;
  const maxCount = 3;
  const shuffled = shuffle(array);
  // fast-shuffle을 사용하여 배열 섞기
  return shuffled.slice(0, getRandomInt(minCount, maxCount));
};
export const productTitles = [
  '무지개 낙하산',
  '아기 스마트 블록',
  '우주 슬라임',
  '마법 퍼즐',
  '별이 빛나는 하늘',
  '파란 유니콘',
  '어둠 속에서 빛나는 별',
  '에픽 로봇 키트',
  '햇살 비치 공',
  '공룡 모험 세트',
  '신나는 물총',
  '발광 팔찌',
  '바다 파도 담요',
  '해적선 모델',
  '우주 탐험가 의상',
  '무지개 연',
  '환상의 성 블록',
  '슈퍼히어로 마스크',
  '정글 사파리 키트',
  '화려한 쌓기 컵',
  '홀로그램 스티커',
  '몬스터 트럭',
  '그림 그리기 패드',
  '동화책',
  '모험 배낭',
  '반짝이는 별 프로젝트',
  '로봇 액션 피규어',
  '자석 건축 타일',
  '무지개 슬라임 키트',
  '드래곤 인형',
  '미스터리 퍼즐 박스',
  '발광 공룡',
  '태양계 모바일',
  '빈티지 기차 세트',
  '나무 실로폰',
  '버블 메이커 기계',
  '우주 셔틀 장난감',
  '마법 지팡이 세트',
  '수중 탐험 키트',
  '동물 왕국 놀이 세트',
  '인터랙티브 어린이 책',
  '레트로 아케이드 게임',
  'LED 디스코 볼',
  '환상 숲 놀이터',
  '미니 굴삭기',
  '슈퍼 우주 로켓',
  '무지개 분필 세트',
  '버블 팝 게임',
  '나무 퍼즐 지도',
  '별빛 지구본',
  '귀여운 테디 베어',
  '로봇 코딩 키트',
  '아쿠아리움 모험 세트',
  '발광 벽 장식',
  '화가를 위한 이젤',
  '공룡 화석 발굴 키트',
  '바다 탐험 조끼',
  '마법 숫자 그림 패드',
  '무지개 롤러 스케이트',
  '정글 체육관 세트',
  '그래피티 미술 키트',
  '발광 스틱 목걸이',
  '환상 요정 지팡이',
  '미니 스케이트보드 세트',
  '스타워즈 모델 키트',
  '반짝이는 보석 키트',
  '와일드 웨스트 기차',
  '동물 왕국 퍼즐',
  '미니 드론',
  '마법 액자',
  '글리터 리본',
  '과학 실험 키트',
  '미스터리 증기 파이프',
  '마법 실내 미끄럼틀',
  '우주 탐사 로봇',
  '화려한 미술 도구',
  '우주 여행 책',
  '부드러운 공 세트',
  '환상 왕국 블록',
  '탐험가 가방',
  '무지개 고무 튜브',
  '미니 기차 트랙',
  '별빛 조명',
  '미니 캠핑 세트',
  '마법 모래 상자',
  '거대한 버블 막대',
  '반짝이는 별 프로젝터',
  '거대한 공룡 퍼즐',
  '마법의 숲 키트',
  '달빛 놀이터',
  '요정 정원 세트',
  '마법 유니콘 퍼즐',
  '빛나는 스틱 팔찌',
  '모험 텐트',
  '작은 탐험가 망원경',
  '꿈틀꿈틀 벌레 장난감',
  '반짝이는 요정 날개',
  '포근한 담요',
  '날아다니는 드래곤 연',
  '마법의 별 조각',
  '스티커 아트 키트',
  '우주 로켓 연',
  '미니 마법 의상',
  '반짝이는 구슬',
  '풍선 공놀이 세트',
  '미니 자동차 경주 세트'
];

export const generateProducts = (): ProductProp[] => {

  const categories: CategoryType[] = [
    'gift',
    'intelligence',
    'fiveSenses',
    'emotion',
    'society',
  ];
  const ageCategories: CategoryAgeType[] = [
    '0-6',
    '7-12',
    '12-18',
    '19-24',
    '2-3',
    'over3',
  ];

  const products: ProductProp[] = [];

  for (let i = 0; i < 100; i++) {
    // 랜덤 이미지 뽑기
    const randomImgPath = imagePaths[getRandomInt(0, imagePaths.length - 1)];

    const product: ProductProp = {
      productId: i + 1,
      productTitle: productTitles[i % productTitles.length],
      productPrice: getRandomInt(3000, 200000),
      productRating: getRandomInt(1, 5),
      productRatingCount: getRandomInt(0, 10000),
      productImg: randomImgPath,
      productCategory: getRandomSubset(categories),
      productCategoryAge: getRandomSubset(ageCategories),
    };
    products.push(product);
  }

  return products;
};

// 고정 목 데이터
// export const tempMockProducts: Product[] = [
//   {
//     productId: 1,
//     productTitle: '제이스랜드 출동 구조대',
//     productPrice: 26700,
//     productRating: 5,
//     productRatingCount: 256,
//     productImg: <img src={exampleImg1} alt='제이스랜드 출동 구조대' />,
//     productCategory: ['intelligence', 'society'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 2,
//     productTitle: '무지개 낙하산',
//     productPrice: 34500,
//     productRating: 4,
//     productRatingCount: 198,
//     productImg: <img src={exampleImg2} alt='무지개 낙하산' />,
//     productCategory: ['emotion', 'fiveSenses'],
//     productCategoryAge: ['12-18', '2-3'],
//   },
//   {
//     productId: 3,
//     productTitle: '베이비 스마트 블록',
//     productPrice: 18200,
//     productRating: 5,
//     productRatingCount: 342,
//     productImg: <img src={exampleImg3} alt='베이비 스마트 블록' />,
//     productCategory: ['fiveSenses'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 4,
//     productTitle: '크리에이티브 몬스터',
//     productPrice: 22700,
//     productRating: 4,
//     productRatingCount: 423,
//     productImg: <img src={exampleImg4} alt='크리에이티브 몬스터' />,
//     productCategory: ['gift'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 5,
//     productTitle: '감각 놀이 세트',
//     productPrice: 15900,
//     productRating: 4,
//     productRatingCount: 287,
//     productImg: <img src={exampleImg5} alt='감각 놀이 세트' />,
//     productCategory: ['fiveSenses'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 6,
//     productTitle: '스마트 학습 로봇',
//     productPrice: 28900,
//     productRating: 3,
//     productRatingCount: 145,
//     productImg: <img src={exampleImg6} alt='스마트 학습 로봇' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 7,
//     productTitle: '미니 레고 세트',
//     productPrice: 13900,
//     productRating: 4,
//     productRatingCount: 212,
//     productImg: <img src={exampleImg7} alt='미니 레고 세트' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 8,
//     productTitle: '액션 피규어',
//     productPrice: 21900,
//     productRating: 2,
//     productRatingCount: 97,
//     productImg: <img src={exampleImg8} alt='액션 피규어' />,
//     productCategory: ['emotion'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 9,
//     productTitle: '레인보우 드론',
//     productPrice: 34900,
//     productRating: 5,
//     productRatingCount: 333,
//     productImg: <img src={exampleImg1} alt='레인보우 드론' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['12-18', '2-3'],
//   },
//   {
//     productId: 10,
//     productTitle: '초코 모형 자동차',
//     productPrice: 17900,
//     productRating: 4,
//     productRatingCount: 255,
//     productImg: <img src={exampleImg2} alt='초코 모형 자동차' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 11,
//     productTitle: '로봇 피규어',
//     productPrice: 23900,
//     productRating: 3,
//     productRatingCount: 170,
//     productImg: <img src={exampleImg3} alt='로봇 피규어' />,
//     productCategory: ['intelligence', 'fiveSenses'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 12,
//     productTitle: '스마트 워치',
//     productPrice: 29900,
//     productRating: 5,
//     productRatingCount: 290,
//     productImg: <img src={exampleImg4} alt='스마트 워치' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 13,
//     productTitle: '캔디 퍼즐',
//     productPrice: 12900,
//     productRating: 4,
//     productRatingCount: 178,
//     productImg: <img src={exampleImg5} alt='캔디 퍼즐' />,
//     productCategory: ['fiveSenses'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 14,
//     productTitle: '미니어처 자동차',
//     productPrice: 15900,
//     productRating: 4,
//     productRatingCount: 225,
//     productImg: <img src={exampleImg6} alt='미니어처 자동차' />,
//     productCategory: ['gift', 'society'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 15,
//     productTitle: '스마트 폰',
//     productPrice: 49900,
//     productRating: 5,
//     productRatingCount: 300,
//     productImg: <img src={exampleImg7} alt='스마트 폰' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 16,
//     productTitle: '인터랙티브 도서',
//     productPrice: 23900,
//     productRating: 3,
//     productRatingCount: 120,
//     productImg: <img src={exampleImg8} alt='인터랙티브 도서' />,
//     productCategory: ['emotion', 'intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 17,
//     productTitle: '미니 드론',
//     productPrice: 34900,
//     productRating: 4,
//     productRatingCount: 185,
//     productImg: <img src={exampleImg1} alt='미니 드론' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 18,
//     productTitle: '블록 놀이 세트',
//     productPrice: 20900,
//     productRating: 5,
//     productRatingCount: 290,
//     productImg: <img src={exampleImg2} alt='블록 놀이 세트' />,
//     productCategory: ['gift', 'fiveSenses'],
//     productCategoryAge: ['2-3'],
//   },
//   {
//     productId: 19,
//     productTitle: '스포츠 자동차',
//     productPrice: 27900,
//     productRating: 4,
//     productRatingCount: 205,
//     productImg: <img src={exampleImg3} alt='스포츠 자동차' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 20,
//     productTitle: '테크놀로지 키트',
//     productPrice: 34900,
//     productRating: 4,
//     productRatingCount: 210,
//     productImg: <img src={exampleImg4} alt='테크놀로지 키트' />,
//     productCategory: ['intelligence', 'fiveSenses'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 21,
//     productTitle: '자동차 레이싱 게임',
//     productPrice: 25900,
//     productRating: 3,
//     productRatingCount: 175,
//     productImg: <img src={exampleImg5} alt='자동차 레이싱 게임' />,
//     productCategory: ['gift'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 22,
//     productTitle: '레고 창작 세트',
//     productPrice: 18900,
//     productRating: 4,
//     productRatingCount: 200,
//     productImg: <img src={exampleImg1} alt='레고 창작 세트' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 22,
//     productTitle: '레고 창작 세트',
//     productPrice: 18900,
//     productRating: 4,
//     productRatingCount: 200,
//     productImg: <img src={exampleImg6} alt='레고 창작 세트' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 23,
//     productTitle: '미니 로봇',
//     productPrice: 31900,
//     productRating: 4,
//     productRatingCount: 185,
//     productImg: <img src={exampleImg7} alt='미니 로봇' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 24,
//     productTitle: '스마트 태블릿',
//     productPrice: 39900,
//     productRating: 5,
//     productRatingCount: 300,
//     productImg: <img src={exampleImg8} alt='스마트 태블릿' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 25,
//     productTitle: '레인보우 로봇',
//     productPrice: 27900,
//     productRating: 3,
//     productRatingCount: 140,
//     productImg: <img src={exampleImg1} alt='레인보우 로봇' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 26,
//     productTitle: '건설 장난감 세트',
//     productPrice: 22900,
//     productRating: 4,
//     productRatingCount: 190,
//     productImg: <img src={exampleImg2} alt='건설 장난감 세트' />,
//     productCategory: ['gift', 'society'],
//     productCategoryAge: ['0-6'],
//   },
//   {
//     productId: 27,
//     productTitle: '미니어처 기차 세트',
//     productPrice: 24900,
//     productRating: 5,
//     productRatingCount: 310,
//     productImg: <img src={exampleImg3} alt='미니어처 기차 세트' />,
//     productCategory: ['gift'],
//     productCategoryAge: ['2-3'],
//   },
//   {
//     productId: 28,
//     productTitle: '인터랙티브 키트',
//     productPrice: 32900,
//     productRating: 3,
//     productRatingCount: 155,
//     productImg: <img src={exampleImg4} alt='인터랙티브 키트' />,
//     productCategory: ['intelligence', 'fiveSenses'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 29,
//     productTitle: '디지털 카메라',
//     productPrice: 43900,
//     productRating: 4,
//     productRatingCount: 220,
//     productImg: <img src={exampleImg5} alt='디지털 카메라' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 30,
//     productTitle: '미니 레이싱카',
//     productPrice: 20900,
//     productRating: 4,
//     productRatingCount: 165,
//     productImg: <img src={exampleImg6} alt='미니 레이싱카' />,
//     productCategory: ['gift', 'fiveSenses'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 31,
//     productTitle: '스마트 펜',
//     productPrice: 17900,
//     productRating: 3,
//     productRatingCount: 130,
//     productImg: <img src={exampleImg7} alt='스마트 펜' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 32,
//     productTitle: '블록 아트 세트',
//     productPrice: 15900,
//     productRating: 4,
//     productRatingCount: 180,
//     productImg: <img src={exampleImg8} alt='블록 아트 세트' />,
//     productCategory: ['emotion', 'fiveSenses'],
//     productCategoryAge: ['2-3'],
//   },
//   {
//     productId: 33,
//     productTitle: '크리에이티브 블록',
//     productPrice: 21900,
//     productRating: 5,
//     productRatingCount: 275,
//     productImg: <img src={exampleImg1} alt='크리에이티브 블록' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 34,
//     productTitle: '모형 비행기',
//     productPrice: 28900,
//     productRating: 3,
//     productRatingCount: 110,
//     productImg: <img src={exampleImg2} alt='모형 비행기' />,
//     productCategory: ['gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 35,
//     productTitle: '스마트 빔프로젝터',
//     productPrice: 39900,
//     productRating: 4,
//     productRatingCount: 200,
//     productImg: <img src={exampleImg3} alt='스마트 빔프로젝터' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 36,
//     productTitle: '디지털 워치',
//     productPrice: 25900,
//     productRating: 5,
//     productRatingCount: 310,
//     productImg: <img src={exampleImg4} alt='디지털 워치' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 37,
//     productTitle: '미니 탱크',
//     productPrice: 22900,
//     productRating: 3,
//     productRatingCount: 140,
//     productImg: <img src={exampleImg5} alt='미니 탱크' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['2-3'],
//   },
//   {
//     productId: 38,
//     productTitle: '스마트 드로잉 패드',
//     productPrice: 31900,
//     productRating: 4,
//     productRatingCount: 200,
//     productImg: <img src={exampleImg6} alt='스마트 드로잉 패드' />,
//     productCategory: ['intelligence', 'fiveSenses'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 39,
//     productTitle: '모형 자동차 세트',
//     productPrice: 24900,
//     productRating: 4,
//     productRatingCount: 185,
//     productImg: <img src={exampleImg7} alt='모형 자동차 세트' />,
//     productCategory: ['gift', 'society'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 40,
//     productTitle: '스마트 로봇 청소기',
//     productPrice: 35900,
//     productRating: 5,
//     productRatingCount: 290,
//     productImg: <img src={exampleImg8} alt='스마트 로봇 청소기' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 41,
//     productTitle: '전기 자동차',
//     productPrice: 42900,
//     productRating: 5,
//     productRatingCount: 320,
//     productImg: <img src={exampleImg1} alt='전기 자동차' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 42,
//     productTitle: '미니 디지털 카메라',
//     productPrice: 29900,
//     productRating: 4,
//     productRatingCount: 2150,
//     productImg: <img src={exampleImg1} alt='미니 디지털 카메라' />,
//     productCategory: ['gift', 'emotion'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 43,
//     productTitle: '로봇 피규어 세트',
//     productPrice: 22900,
//     productRating: 4,
//     productRatingCount: 1850,
//     productImg: <img src={exampleImg2} alt='로봇 피규어 세트' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 44,
//     productTitle: '자동차 시뮬레이터',
//     productPrice: 33900,
//     productRating: 3,
//     productRatingCount: 1500,
//     productImg: <img src={exampleImg3} alt='자동차 시뮬레이터' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 45,
//     productTitle: '스마트 안경',
//     productPrice: 109000,
//     productRating: 4,
//     productRatingCount: 5200,
//     productImg: <img src={exampleImg4} alt='스마트 안경' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 46,
//     productTitle: '레고 로봇 세트',
//     productPrice: 149000,
//     productRating: 5,
//     productRatingCount: 6500,
//     productImg: <img src={exampleImg5} alt='레고 로봇 세트' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['7-12'],
//   },
//   {
//     productId: 47,
//     productTitle: '스마트 홈 시스템',
//     productPrice: 199000,
//     productRating: 4,
//     productRatingCount: 7400,
//     productImg: <img src={exampleImg6} alt='스마트 홈 시스템' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 48,
//     productTitle: '3D 프린터 키트',
//     productPrice: 159000,
//     productRating: 5,
//     productRatingCount: 5300,
//     productImg: <img src={exampleImg7} alt='3D 프린터 키트' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 49,
//     productTitle: '스마트 스피커',
//     productPrice: 129000,
//     productRating: 4,
//     productRatingCount: 4200,
//     productImg: <img src={exampleImg8} alt='스마트 스피커' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 50,
//     productTitle: '전기 자전거',
//     productPrice: 199000,
//     productRating: 5,
//     productRatingCount: 5500,
//     productImg: <img src={exampleImg1} alt='전기 자전거' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 51,
//     productTitle: '스마트 홈 카메라',
//     productPrice: 149000,
//     productRating: 3,
//     productRatingCount: 5300,
//     productImg: <img src={exampleImg2} alt='스마트 홈 카메라' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 52,
//     productTitle: '디지털 음악 플레이어',
//     productPrice: 119000,
//     productRating: 4,
//     productRatingCount: 4800,
//     productImg: <img src={exampleImg3} alt='디지털 음악 플레이어' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 53,
//     productTitle: '미니 드론',
//     productPrice: 99000,
//     productRating: 5,
//     productRatingCount: 3500,
//     productImg: <img src={exampleImg4} alt='미니 드론' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['12-18'],
//   },
//   {
//     productId: 54,
//     productTitle: '고급 스마트폰',
//     productPrice: 179000,
//     productRating: 5,
//     productRatingCount: 6800,
//     productImg: <img src={exampleImg5} alt='고급 스마트폰' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 55,
//     productTitle: 'VR 헤드셋',
//     productPrice: 129000,
//     productRating: 4,
//     productRatingCount: 5600,
//     productImg: <img src={exampleImg6} alt='VR 헤드셋' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 56,
//     productTitle: '고성능 노트북',
//     productPrice: 199000,
//     productRating: 5,
//     productRatingCount: 7200,
//     productImg: <img src={exampleImg7} alt='고성능 노트북' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 57,
//     productTitle: '스마트 체중계',
//     productPrice: 89000,
//     productRating: 3,
//     productRatingCount: 3100,
//     productImg: <img src={exampleImg8} alt='스마트 체중계' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 58,
//     productTitle: '휴대용 프로젝터',
//     productPrice: 109000,
//     productRating: 4,
//     productRatingCount: 4500,
//     productImg: <img src={exampleImg1} alt='휴대용 프로젝터' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 59,
//     productTitle: '스마트 로봇 청소기',
//     productPrice: 139000,
//     productRating: 4,
//     productRatingCount: 5200,
//     productImg: <img src={exampleImg2} alt='스마트 로봇 청소기' />,
//     productCategory: ['intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 60,
//     productTitle: '스마트 테이블',
//     productPrice: 139000,
//     productRating: 4,
//     productRatingCount: 5000,
//     productImg: <img src={exampleImg3} alt='스마트 테이블' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 61,
//     productTitle: '4K TV',
//     productPrice: 179000,
//     productRating: 5,
//     productRatingCount: 6000,
//     productImg: <img src={exampleImg4} alt='4K TV' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 62,
//     productTitle: '스마트 미러',
//     productPrice: 169000,
//     productRating: 4,
//     productRatingCount: 4800,
//     productImg: <img src={exampleImg5} alt='스마트 미러' />,
//     productCategory: ['intelligence', 'gift'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 63,
//     productTitle: '스마트 LED 조명',
//     productPrice: 37900,
//     productRating: 4,
//     productRatingCount: 335,
//     productImg: <img src={exampleImg1} alt='스마트 LED 조명' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 64,
//     productTitle: '블루투스 스피커',
//     productPrice: 24900,
//     productRating: 3,
//     productRatingCount: 782,
//     productImg: <img src={exampleImg2} alt='블루투스 스피커' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 65,
//     productTitle: '무선 이어폰',
//     productPrice: 54900,
//     productRating: 5,
//     productRatingCount: 1237,
//     productImg: <img src={exampleImg3} alt='무선 이어폰' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 66,
//     productTitle: '휴대용 충전기',
//     productPrice: 17900,
//     productRating: 4,
//     productRatingCount: 543,
//     productImg: <img src={exampleImg4} alt='휴대용 충전기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 67,
//     productTitle: '스마트 체중계',
//     productPrice: 26900,
//     productRating: 3,
//     productRatingCount: 1349,
//     productImg: <img src={exampleImg5} alt='스마트 체중계' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 68,
//     productTitle: '고급 헤드폰',
//     productPrice: 69900,
//     productRating: 5,
//     productRatingCount: 2382,
//     productImg: <img src={exampleImg6} alt='고급 헤드폰' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 69,
//     productTitle: '스마트 냉장고',
//     productPrice: 79900,
//     productRating: 4,
//     productRatingCount: 945,
//     productImg: <img src={exampleImg7} alt='스마트 냉장고' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 70,
//     productTitle: '미니 프로젝터',
//     productPrice: 59900,
//     productRating: 4,
//     productRatingCount: 2146,
//     productImg: <img src={exampleImg8} alt='미니 프로젝터' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 71,
//     productTitle: '전기 주전자',
//     productPrice: 29900,
//     productRating: 3,
//     productRatingCount: 789,
//     productImg: <img src={exampleImg1} alt='전기 주전자' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 72,
//     productTitle: '스마트 조명',
//     productPrice: 46900,
//     productRating: 5,
//     productRatingCount: 1542,
//     productImg: <img src={exampleImg2} alt='스마트 조명' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 73,
//     productTitle: '휴대용 공기청정기',
//     productPrice: 35900,
//     productRating: 4,
//     productRatingCount: 593,
//     productImg: <img src={exampleImg3} alt='휴대용 공기청정기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 74,
//     productTitle: '스마트 체온계',
//     productPrice: 24900,
//     productRating: 5,
//     productRatingCount: 1816,
//     productImg: <img src={exampleImg4} alt='스마트 체온계' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 75,
//     productTitle: '스마트 전구',
//     productPrice: 19900,
//     productRating: 4,
//     productRatingCount: 623,
//     productImg: <img src={exampleImg5} alt='스마트 전구' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 76,
//     productTitle: '휴대용 모니터',
//     productPrice: 74900,
//     productRating: 3,
//     productRatingCount: 1112,
//     productImg: <img src={exampleImg6} alt='휴대용 모니터' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 77,
//     productTitle: '스마트 미러',
//     productPrice: 62900,
//     productRating: 5,
//     productRatingCount: 1427,
//     productImg: <img src={exampleImg7} alt='스마트 미러' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 78,
//     productTitle: '고속 충전기',
//     productPrice: 17900,
//     productRating: 4,
//     productRatingCount: 995,
//     productImg: <img src={exampleImg8} alt='고속 충전기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 79,
//     productTitle: '스마트 도어벨',
//     productPrice: 47900,
//     productRating: 4,
//     productRatingCount: 2113,
//     productImg: <img src={exampleImg1} alt='스마트 도어벨' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 80,
//     productTitle: '휴대용 프로젝터',
//     productPrice: 74900,
//     productRating: 5,
//     productRatingCount: 1189,
//     productImg: <img src={exampleImg2} alt='휴대용 프로젝터' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 81,
//     productTitle: '스마트 식기세척기',
//     productPrice: 79900,
//     productRating: 4,
//     productRatingCount: 4738,
//     productImg: <img src={exampleImg3} alt='스마트 식기세척기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 82,
//     productTitle: '스마트 로봇 청소기',
//     productPrice: 64900,
//     productRating: 5,
//     productRatingCount: 1347,
//     productImg: <img src={exampleImg4} alt='스마트 로봇 청소기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
//   {
//     productId: 83,
//     productTitle: '스마트 공기청정기',
//     productPrice: 55900,
//     productRating: 4,
//     productRatingCount: 731,
//     productImg: <img src={exampleImg5} alt='스마트 공기청정기' />,
//     productCategory: ['gift', 'intelligence'],
//     productCategoryAge: ['19-24'],
//   },
// ];
